import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { ApiClient } from "../api.js";

export function register(server: McpServer, api: ApiClient): void {
  server.tool(
    "detect_ai",
    "Detect whether media content was generated by AI. Supports images, video, audio, " +
      "and text/PDF. Runs multiple specialized detection models in parallel for the given " +
      "media type. Returns a job_id — use check_job to poll for results.",
    {
      media_url: z
        .string()
        .url()
        .optional()
        .describe("Public URL of the media to analyze"),
      media: z
        .string()
        .optional()
        .describe("Base64-encoded media content to analyze"),
      text: z
        .string()
        .optional()
        .describe("Plain text content to analyze for AI generation"),
      mime: z
        .string()
        .optional()
        .describe("MIME type of the media (e.g. image/png, audio/wav, text/plain)"),
      tags: z
        .array(z.string())
        .optional()
        .describe("Tags for organizing and filtering"),
    },
    async (params) => {
      try {
        const body: Record<string, unknown> = {};
        if (params.media_url) body.media_url = params.media_url;
        if (params.media) body.media = params.media;
        if (params.text) body.text = params.text;
        if (params.mime) body.mime = params.mime;
        if (params.tags) body.tags = params.tags;

        const result = await api.post("/api/v1/detect/ai", body);
        const res = result as { job_id: string };

        return {
          content: [
            {
              type: "text" as const,
              text:
                `AI detection job created.\n\n` +
                `Job ID: ${res.job_id}\n\n` +
                `Use check_job with this job_id to poll for results.`,
            },
          ],
        };
      } catch (err) {
        return {
          content: [
            {
              type: "text" as const,
              text: `Error: ${err instanceof Error ? err.message : String(err)}`,
            },
          ],
          isError: true as const,
        };
      }
    },
  );
}
